# Generated by Django 2.2 on 2021-02-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color_identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_identity', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Legalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalities', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manacost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manacost', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_line', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set_acronym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_acronym', models.CharField(blank=True, max_length=50, null=True)),
                ('set_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acronyms', to='mtg_app.Set_type')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cmc', models.CharField(blank=True, max_length=5, null=True)),
                ('power', models.CharField(blank=True, max_length=3, null=True)),
                ('toughness', models.CharField(blank=True, max_length=3, null=True)),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('oracle_text', models.TextField(blank=True, null=True)),
                ('img_art_crop_url', models.URLField(max_length=300, null=True)),
                ('img_border_crop_url', models.URLField(max_length=300, null=True)),
                ('img_large_url', models.URLField(max_length=300, null=True)),
                ('img_png_url', models.URLField(max_length=300, null=True)),
                ('img_small_url', models.URLField(max_length=300, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Artist')),
                ('color_identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Color_identity')),
                ('colors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Colors')),
                ('digital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Digital')),
                ('keywords', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Keywords')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Language')),
                ('legalities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Legalities')),
                ('manacost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Manacost')),
                ('rarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Rarity')),
                ('set_acronym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Set_acronym')),
                ('type_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Type_line')),
            ],
        ),
    ]
